### ISSUE TITLE
运行代码报错

### ISSUE THREAD

**Issue by s192516** [cocowool/mp3tag#1]
您好, 我安装模块后执行
mpt = mp3tag()
报错
'module' object is not callable
请问该如何解决

**Comment by cocowool** [comment]
能把具体的环境信息贴一下么，我回去了看看



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: s192516 ***@***.***&gt;
发送时间: 2022年10月22日 14:35
收件人: cocowool/mp3tag ***@***.***&gt;
抄送: Subscribed ***@***.***&gt;
主题: Re: [cocowool/mp3tag] 运行代码报错 (Issue #1)





 
您好, 我安装模块后执行
 mpt = mp3tag()
 报错
 'module' object is not callable
 请问该如何解决

**Comment by cocowool** [comment]
感谢您的反馈，做了一些修改优化，请按照最新的提示试一下，谢谢。
